=== christoffertoppe/xml/src/xmljaskeema/Vuodenajat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Skeema esimerkki
-->
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema" elementFormDefault = "qualified">

    
      <!-- elementti "nimi" sisÃ¤ltÃ¤Ã¤ tekstiÃ¤ ja attribuutin "tyyppi" -->
      
  <xsd:element name ="nimi">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name ="vuodenaika" type ="xsd:string" use ="optional"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name ="kesto" type = "xsd:string"/>

  <xsd:complexType name = "vuodenaika">
    <xsd:sequence>
      <xsd:element ref ="nimi"/>
      <xsd:element ref ="kesto"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name = "vuodenajat">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name = "vuodenaika" type = "vuodenaika" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== christoffertoppe/xml/src/xmljaskeema/XMLtiedosto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
XML ja DTD esimerkki
-->

<vuodenajat xmlns= "" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Vuodenajat.xsd">
    <vuodenaika>
        <nimi vuodenaika = "Kev채t">Kev채t
        </nimi>
        <kesto>3 kk
        </kesto>
    </vuodenaika>
    <vuodenaika>
        <nimi vuodenaika = "Kes채">Kes채
        </nimi>
        <kesto>3 kk
        </kesto>
    </vuodenaika>
    <vuodenaika>
        <nimi vuodenaika = "Syksy">Syksy
        </nimi>
        <kesto>3 kk
        </kesto>
    </vuodenaika>
    <vuodenaika>
        <nimi vuodenaika = "Talvi">Talvi
        </nimi>
        <kesto>3 kk
        </kesto>
    </vuodenaika>
</vuodenajat>
